function main() {
    var host = "n00dles";

    var avg_money = getServerMoneyAvailable(host);
    var avg_security = getServerSecurityLevel(host);
    while (true) {
        avg_money = 0.99 * avg_money + 0.01 * getServerMoneyAvailable(host);
        avg_security = 0.99 * avg_security + 0.01 * getServerSecurityLevel(host);
        tprintf("money=%s, security=%f", nFormat(avg_money, "0.000a"), avg_security);
        sleep(5 * 1000);
    }
}

main();